### PR TITLE
Fix function inline errors in debug optimization (-Og)

### PR DESCRIPTION
**Pull request by Yashinde145**
- Fixes issue #256 

Compiler does not inline any functions when using debug optimization (-Og). Hence, remove -Winline flag when compiling with debug optimization.

### CODE REVIEW

**Comment by Yashinde145** [comment]
@rgerhards Please review the PR.

**Comment by rgerhards** [comment]
This sounds OK and I appreciate the patch. Just curios: what is the core reason for patching this? Is it "just" to do the right thing, or did you experience any erros/annoyances? Would be good to know as I do not see any issues, also not in CI.

**Comment by Yashinde145** [comment]
As mentioned in issue #256, the error was found for inlining functions in Yocto librelp sources for DEBUG build. Thanks.

**Comment by Yashinde145** [comment]
Hi @rgerhards, I think the centos 8 and fedora 36 checks did not initiate. Can you please re-run it?

**Comment by rgerhards** [comment]
I'll check what's going on.

**Comment by rgerhards** [comment]
I think I know what is wrong with the two failing CI runs. The workflow has too-old ubuntu versions specified. I think it is OK to merge without them. Will also check and see that I can fix the CI issue.

**Comment by rgerhards** [comment]
FYI The CI issue is fixed via #259. But I don't see any reason to rebase and re-run CI.

**Review by rgerhards — APPROVED** [review]

**Comment by rgerhards** [comment]
Thx again for the PR! Much appreciated.

**Comment by Yashinde145** [comment]
Thanks for checking and accepting PR!

**Pull request merged**
