### PR TITLE
Ability to set a optional bindAddr

### PR DESCRIPTION
**Pull request by perlei**

### CODE REVIEW

**Comment by rgerhards** [comment]
Thx for the PR. We are currently working on both librelp and the CI. So you may see some errors in CI that are not real and I may also ask for a rebase (or will do a merge PR). It may also take a short while for me to review and finally merge. Just so that you know.

**Comment by perlei** [comment]
np

**Comment by rgerhards** [comment]
The travis failure is real, there is at least one line that is too long (we enforce at least part of the code style via CI).

**Comment by perlei** [comment]
ok relpsrv.c:394 was split

**Pull request merged**
