### PR TITLE
Adding other signature for the fingerprint mode in relp

### PR DESCRIPTION
**Pull request by briaeros**
Hello,

TLS Fingreprint in relp is still based (hardcoded) on the old (and now obsolete) SHA1.

I've tried to modify the code a little bit so
- The signature algorithm is now dynamic (using the gnutls name ). We can use SHA256, or any other (less than 31 char) gnutls' recognized hash names .
- We can have different types of signatures in the same "PermittedPeers" (maximum 10, hardcoded in a define).

The first trade-off is the fact that I've done a crude algorithm. I test each permittedpeers with all the possible signatures (all algorithm we have discovered in the permittedPeers) . I've estimated that, as the code is run only at the initialization of the session and the low number of concurrent algorithms, the overhead is reasonable. In most case (sames algorithm everywhere), we will only scan two times permittedPeers instead of only once.

The second trade-off is the limited testing ability I've got to debug the code. I've tried to check each of my bounds and other limits, but a bug can always lurks somewhere. And I didn't do a proper "test program" to verify  each and every possibles cases. I did test with womewhat invalid signatures, with no problem detected, but I didn't try any fuzzing.

Feel to free to point me on what I must change to the code so it agree with rsyslog's development standards :)

Cordially

### CODE REVIEW

**Comment by rgerhards** [comment]
@briaeros sorry for the veeeeeery long delay. Believe it or not, I would still be interested in merging this, however I have a couple of questions. As so much time passed, I just wanted to ask if you are still interested in getting this merged and working together to get it done. I could fully understand if not...

**Comment by briaeros** [comment]
Hi, I'm still interested , even if I didn't touch my pull request  and make it live:).
I hope I could answer your questions in a satisfying way.

**Comment by rgerhards** [comment]
@briaeros thanks. Let's start with two things:

* probably I overlook something, but does the patch default to old behaviour? I have the impression that it changes it to new
* it would be great if you could rebase to current master

Again, if you do not have time at the moment, no problem. I'll then see how far I can come on my own.

**Comment by briaeros** [comment]
Hi,
I've done a quick merge, but I didn't validate it on my machine. At least , the CI is successful.
I had already modified the api of GenFingerprintStr, so I kept it this way.


I'm not sure I understood clearly what is the "old behaviour" vs the "new one".
So, I hope that the next explicative sentences aren't too much "off the mark".

The actual usage of fingerprint is well behaved since it already uses the gnutls digest type (hard-coded) on the fingerprint.

In this patch, instead of hard-coding the digest, we list all the digests used in permittedpeers, then we create as many fingerprints as necessary .

As this is dynamic, an "old config file" is totally compatible. It will set only "SHA1" in listSigPeer, and all the comparison part will be globally similar

**Comment by rgerhards** [comment]
@briaeros thx, this seems to address my concerns. Another review also did not bring up any real issues...

**Comment by rgerhards** [comment]
having more tests would of course be better, but now that it is in master, the rsyslog CI will also pick it up. It has additional tests. If problems come up, I can revert.

**Pull request merged**
